name: Run Tests (ccipy-utils)

on:
  push:
    branches: [ "main", "feat/*" ]
  pull_request:

jobs:
  run-tests:
    uses: ./.github/workflows/test-base.yml
    with:
      project: ccipy-utils
      python-version: "3.12"